[workspace]
resolver = "2"

members = [
    "aoc21",
    "aoc22",
    "util",
]

[workspace.dependencies]
regex = "1.9.5"
itertools = "0.11.0"
num-traits = "0.2.16"
rayon = "1.8.0"
num-complex = "0.4.4"