[workspace]
resolver = "2"

members = [
    "aoc16",
    "aoc21",
    "aoc22",
    "aoc23",
    "util",
]

[workspace.dependencies]
regex = "1.9.5"
fancy-regex = "0.12.0"
itertools = "0.11.0"
num-traits = "0.2.16"
rayon = "1.8.0"
num-complex = "0.4.4"
lazy_static = "1.4.0"
md5 = "0.7.0"